services:
  app:
    build:
      context: .
    container_name: "e_medicine_app"
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 9092:9092

  db:
    image: postgres:16
    container_name: "e_medicine_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5439:5432

volumes:
  postgres_data:
