services:
  app:
    build:
      context: .
    container_name: "e_medicine_app"
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - ./media:/app/media
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 9092:9092

  db:
    image: postgres:16
    container_name: "e_medicine_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5439:5432

  bot:
    build:
      context: ./bot  # Path to the bot's directory
    container_name: "e_medicine_bot"
    restart: always
    command: python bot.py  # Ensure bot starts correctly
    volumes:
      - ./bot:/bot  # Mount bot directory
    working_dir: /bot  # Ensure bot runs from its directory
    env_file:
      - .env  # Use the same env file as Django
    depends_on:
      - db  # Ensure DB is ready before starting bot
    networks:
      - default  # Connects to the same Docker network

volumes:
  postgres_data:
