# Generated by Django 5.1.4 on 2025-02-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tg_nick',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
