# Generated by Django 5.1.4 on 2025-02-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_client_tg_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
