# Generated by Django 5.1.4 on 2025-02-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_img_64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'ordered'), ('on_the_way', 'on_the_way'), ('completed', 'completed'), ('rejected', 'rejected'), ('new', 'new')], max_length=100),
        ),
    ]
