# Generated by Django 5.1.4 on 2026-04-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tg_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
