# Generated by Django 5.2.17 on 2026-09-30 08:12

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('delivery_time', models.CharField(blank=True, default='30–45', max_length=20)),
                ('min_order', models.PositiveIntegerField(default=0)),
                ('brand_color', models.CharField(blank=True, max_length=7)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('owner_phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_setups', to='hub.business')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('kind', models.CharField(choices=[('shop', 'Shop'), ('admin', 'Admin panel'), ('platform', 'Platform panel')], default='shop', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='hub.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Customers'), ('admin', 'Staff')], max_length=10)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('token_encrypted', models.TextField()),
                ('created_via', models.CharField(default='token', max_length=10)),
                ('owner_telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='hub.business')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('business', 'role'), name='hub_one_bot_per_role')],
            },
        ),
    ]
