# Generated by Django 5.2.17 on 2026-10-02 14:53

import apps.platform.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, storage=apps.platform.storage.PlatformStorage(), upload_to='logos/'),
        ),
    ]
