# Generated by Django 5.1.4 on 2025-02-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
