# Generated by Django 5.1.4 on 2025-02-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed',
        ),
    ]
