# Generated by Django 5.2.17 on 2026-09-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotHeartbeat',
        ),
    ]
