# Generated by Django 5.2.17 on 2026-10-02 14:53

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0002_delete_botheartbeat'),
        ('app', '0018_web_shop_and_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order_created', 'Order placed'), ('order_status', 'Order status changed')], max_length=30)),
                ('event', models.CharField(blank=True, db_default='', default='', max_length=30)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(db_default=0, default=0)),
                ('error', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.order')),
            ],
            options={
                'indexes': [models.Index(fields=['sent_at', 'id'], name='adminbot_outbox_pending')],
            },
        ),
    ]
